apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apple
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apple
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stage/apple
    repoURL: https://github.com/cisco-sfcn/gitops-poc.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
