apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-metrics
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.20.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apple
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
